# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/STORAGE/Compilers/CCompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/STORAGE/Compilers/CCompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/STORAGE/Compilers/CCompiler/CMakeFiles /Volumes/STORAGE/Compilers/CCompiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/STORAGE/Compilers/CCompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CCompiler

# Build rule for target.
CCompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CCompiler
.PHONY : CCompiler

# fast build rule for target.
CCompiler/fast:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/build
.PHONY : CCompiler/fast

assembly.o: assembly.cpp.o

.PHONY : assembly.o

# target to build an object file
assembly.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assembly.cpp.o
.PHONY : assembly.cpp.o

assembly.i: assembly.cpp.i

.PHONY : assembly.i

# target to preprocess a source file
assembly.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assembly.cpp.i
.PHONY : assembly.cpp.i

assembly.s: assembly.cpp.s

.PHONY : assembly.s

# target to generate assembly for a file
assembly.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assembly.cpp.s
.PHONY : assembly.cpp.s

assemblycontext.o: assemblycontext.cpp.o

.PHONY : assemblycontext.o

# target to build an object file
assemblycontext.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assemblycontext.cpp.o
.PHONY : assemblycontext.cpp.o

assemblycontext.i: assemblycontext.cpp.i

.PHONY : assemblycontext.i

# target to preprocess a source file
assemblycontext.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assemblycontext.cpp.i
.PHONY : assemblycontext.cpp.i

assemblycontext.s: assemblycontext.cpp.s

.PHONY : assemblycontext.s

# target to generate assembly for a file
assemblycontext.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/assemblycontext.cpp.s
.PHONY : assemblycontext.cpp.s

ccompiler.o: ccompiler.cpp.o

.PHONY : ccompiler.o

# target to build an object file
ccompiler.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ccompiler.cpp.o
.PHONY : ccompiler.cpp.o

ccompiler.i: ccompiler.cpp.i

.PHONY : ccompiler.i

# target to preprocess a source file
ccompiler.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ccompiler.cpp.i
.PHONY : ccompiler.cpp.i

ccompiler.s: ccompiler.cpp.s

.PHONY : ccompiler.s

# target to generate assembly for a file
ccompiler.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ccompiler.cpp.s
.PHONY : ccompiler.cpp.s

cexpression.o: cexpression.cpp.o

.PHONY : cexpression.o

# target to build an object file
cexpression.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cexpression.cpp.o
.PHONY : cexpression.cpp.o

cexpression.i: cexpression.cpp.i

.PHONY : cexpression.i

# target to preprocess a source file
cexpression.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cexpression.cpp.i
.PHONY : cexpression.cpp.i

cexpression.s: cexpression.cpp.s

.PHONY : cexpression.s

# target to generate assembly for a file
cexpression.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cexpression.cpp.s
.PHONY : cexpression.cpp.s

cparser.o: cparser.cpp.o

.PHONY : cparser.o

# target to build an object file
cparser.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cparser.cpp.o
.PHONY : cparser.cpp.o

cparser.i: cparser.cpp.i

.PHONY : cparser.i

# target to preprocess a source file
cparser.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cparser.cpp.i
.PHONY : cparser.cpp.i

cparser.s: cparser.cpp.s

.PHONY : cparser.s

# target to generate assembly for a file
cparser.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cparser.cpp.s
.PHONY : cparser.cpp.s

cscanner.o: cscanner.cpp.o

.PHONY : cscanner.o

# target to build an object file
cscanner.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cscanner.cpp.o
.PHONY : cscanner.cpp.o

cscanner.i: cscanner.cpp.i

.PHONY : cscanner.i

# target to preprocess a source file
cscanner.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cscanner.cpp.i
.PHONY : cscanner.cpp.i

cscanner.s: cscanner.cpp.s

.PHONY : cscanner.s

# target to generate assembly for a file
cscanner.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/cscanner.cpp.s
.PHONY : cscanner.cpp.s

grammar.o: grammar.cpp.o

.PHONY : grammar.o

# target to build an object file
grammar.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammar.cpp.o
.PHONY : grammar.cpp.o

grammar.i: grammar.cpp.i

.PHONY : grammar.i

# target to preprocess a source file
grammar.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammar.cpp.i
.PHONY : grammar.cpp.i

grammar.s: grammar.cpp.s

.PHONY : grammar.s

# target to generate assembly for a file
grammar.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammar.cpp.s
.PHONY : grammar.cpp.s

grammartree.o: grammartree.cpp.o

.PHONY : grammartree.o

# target to build an object file
grammartree.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammartree.cpp.o
.PHONY : grammartree.cpp.o

grammartree.i: grammartree.cpp.i

.PHONY : grammartree.i

# target to preprocess a source file
grammartree.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammartree.cpp.i
.PHONY : grammartree.cpp.i

grammartree.s: grammartree.cpp.s

.PHONY : grammartree.s

# target to generate assembly for a file
grammartree.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/grammartree.cpp.s
.PHONY : grammartree.cpp.s

instructions.o: instructions.cpp.o

.PHONY : instructions.o

# target to build an object file
instructions.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/instructions.cpp.o
.PHONY : instructions.cpp.o

instructions.i: instructions.cpp.i

.PHONY : instructions.i

# target to preprocess a source file
instructions.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/instructions.cpp.i
.PHONY : instructions.cpp.i

instructions.s: instructions.cpp.s

.PHONY : instructions.s

# target to generate assembly for a file
instructions.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/instructions.cpp.s
.PHONY : instructions.cpp.s

ir.o: ir.cpp.o

.PHONY : ir.o

# target to build an object file
ir.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ir.cpp.o
.PHONY : ir.cpp.o

ir.i: ir.cpp.i

.PHONY : ir.i

# target to preprocess a source file
ir.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ir.cpp.i
.PHONY : ir.cpp.i

ir.s: ir.cpp.s

.PHONY : ir.s

# target to generate assembly for a file
ir.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/ir.cpp.s
.PHONY : ir.cpp.s

parsetree.o: parsetree.cpp.o

.PHONY : parsetree.o

# target to build an object file
parsetree.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/parsetree.cpp.o
.PHONY : parsetree.cpp.o

parsetree.i: parsetree.cpp.i

.PHONY : parsetree.i

# target to preprocess a source file
parsetree.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/parsetree.cpp.i
.PHONY : parsetree.cpp.i

parsetree.s: parsetree.cpp.s

.PHONY : parsetree.s

# target to generate assembly for a file
parsetree.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/parsetree.cpp.s
.PHONY : parsetree.cpp.s

statetablegenerator.o: statetablegenerator.cpp.o

.PHONY : statetablegenerator.o

# target to build an object file
statetablegenerator.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetablegenerator.cpp.o
.PHONY : statetablegenerator.cpp.o

statetablegenerator.i: statetablegenerator.cpp.i

.PHONY : statetablegenerator.i

# target to preprocess a source file
statetablegenerator.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetablegenerator.cpp.i
.PHONY : statetablegenerator.cpp.i

statetablegenerator.s: statetablegenerator.cpp.s

.PHONY : statetablegenerator.s

# target to generate assembly for a file
statetablegenerator.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetablegenerator.cpp.s
.PHONY : statetablegenerator.cpp.s

statetables.o: statetables.cpp.o

.PHONY : statetables.o

# target to build an object file
statetables.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetables.cpp.o
.PHONY : statetables.cpp.o

statetables.i: statetables.cpp.i

.PHONY : statetables.i

# target to preprocess a source file
statetables.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetables.cpp.i
.PHONY : statetables.cpp.i

statetables.s: statetables.cpp.s

.PHONY : statetables.s

# target to generate assembly for a file
statetables.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/statetables.cpp.s
.PHONY : statetables.cpp.s

symboltable.o: symboltable.cpp.o

.PHONY : symboltable.o

# target to build an object file
symboltable.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/symboltable.cpp.o
.PHONY : symboltable.cpp.o

symboltable.i: symboltable.cpp.i

.PHONY : symboltable.i

# target to preprocess a source file
symboltable.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/symboltable.cpp.i
.PHONY : symboltable.cpp.i

symboltable.s: symboltable.cpp.s

.PHONY : symboltable.s

# target to generate assembly for a file
symboltable.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/symboltable.cpp.s
.PHONY : symboltable.cpp.s

token.o: token.cpp.o

.PHONY : token.o

# target to build an object file
token.cpp.o:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/token.cpp.o
.PHONY : token.cpp.o

token.i: token.cpp.i

.PHONY : token.i

# target to preprocess a source file
token.cpp.i:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/token.cpp.i
.PHONY : token.cpp.i

token.s: token.cpp.s

.PHONY : token.s

# target to generate assembly for a file
token.cpp.s:
	$(MAKE) -f CMakeFiles/CCompiler.dir/build.make CMakeFiles/CCompiler.dir/token.cpp.s
.PHONY : token.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CCompiler"
	@echo "... assembly.o"
	@echo "... assembly.i"
	@echo "... assembly.s"
	@echo "... assemblycontext.o"
	@echo "... assemblycontext.i"
	@echo "... assemblycontext.s"
	@echo "... ccompiler.o"
	@echo "... ccompiler.i"
	@echo "... ccompiler.s"
	@echo "... cexpression.o"
	@echo "... cexpression.i"
	@echo "... cexpression.s"
	@echo "... cparser.o"
	@echo "... cparser.i"
	@echo "... cparser.s"
	@echo "... cscanner.o"
	@echo "... cscanner.i"
	@echo "... cscanner.s"
	@echo "... grammar.o"
	@echo "... grammar.i"
	@echo "... grammar.s"
	@echo "... grammartree.o"
	@echo "... grammartree.i"
	@echo "... grammartree.s"
	@echo "... instructions.o"
	@echo "... instructions.i"
	@echo "... instructions.s"
	@echo "... ir.o"
	@echo "... ir.i"
	@echo "... ir.s"
	@echo "... parsetree.o"
	@echo "... parsetree.i"
	@echo "... parsetree.s"
	@echo "... statetablegenerator.o"
	@echo "... statetablegenerator.i"
	@echo "... statetablegenerator.s"
	@echo "... statetables.o"
	@echo "... statetables.i"
	@echo "... statetables.s"
	@echo "... symboltable.o"
	@echo "... symboltable.i"
	@echo "... symboltable.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

